name: my_afse
description: The AFSE integrated JumpRope client.

publish_to: "none"

version: 2.3.0

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  expandable: ^5.0.1
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter_colorpicker: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_linkify: ^5.0.2
  flutter_native_splash: ^2.0.1+1
  flutter_settings_ui: ^2.0.1
  flutter_shortcuts: ^1.3.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.3
  icalendar_parser: ^1.0.1+1
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  ota_update: ^4.0.1
  package_info_plus: ^1.0.4
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.18
  version: ^2.0.0
  webfeed: ^0.7.0

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/ios.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "#212121"

flutter_native_splash:
  image: "assets/icon/logo.png"
  color: "#212121"

flutter:
  uses-material-design: true

  assets:
    - "assets/icon/"
    - "assets/img/"
    - "assets/shortcut/"
