name: my_afse
description: The AFSE integrated JumpRope client.

publish_to: "none"

version: 2.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_shortcuts: ^1.2.2
  provider: ^6.0.0
  http: ^0.13.3
  intl: ^0.17.0
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_analytics: ^8.2.0
  firebase_database: ^7.1.2
  pull_to_refresh: ^2.0.0
  flutter_linkify: ^5.0.2
  icalendar_parser: ^0.8.0+1
  webfeed: ^0.7.0
  universal_html: ^2.0.8
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  settings_ui: ^1.0.0
  flutter_colorpicker: ^0.5.0
  expandable: ^5.0.1
  linked_scroll_controller: ^0.2.0
  package_info_plus: ^1.0.4
  version: ^2.0.0
  ota_update: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/ios.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "#212121"

flutter_native_splash:
  image: "assets/icon/logo.png"
  color: "#212121"

flutter:
  uses-material-design: true

  assets:
    - "assets/icon/"
    - "assets/img/"
    - "assets/shortcut/"
