name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 12.x

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.0
      - run: flutter config --no-analytics
      - run: flutter pub get

      - name: Setup Android
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > android/key.properties
          echo "${{ secrets.FIREBASE_JSON }}" | base64 --decode > android/app/google-services.json

      # - name: Run Test
      #   run: flutter test

      - name: Build APK
        run:
          flutter build apk --target-platform
          android-arm,android-arm64,android-x64 --split-per-abi

      - name: Release Artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app.apk
