name: CI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.0
      - run: flutter pub get
      - run: flutter test
      - run:
          flutter build apk --target-platform
          android-arm,android-arm64,android-x64 --split-per-abi
