name: CI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.0
      - run: flutter pub get --suppress-analytics
      - name: Setup Android Keys
        working-directory: dev/mobile_app
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${GITHUB_WORKSPACE}/android/app/key.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > ${GITHUB_WORKSPACE}/android/key.properties
          echo "${{ secrets.FIREBASE_JSON }}" | base64 --decode > ${GITHUB_WORKSPACE}/android/app/google-services.json
      # - run: flutter test
      - run:
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app.apk
